### ISSUE TITLE
restoreTxs Error,

### ISSUE THREAD

**Issue by lhfbc** [wunder3605/iri#195]
When starting iri, the following logs will appear.

03/08 11:42:01.578 [pool-3-thread-3] INFO  Node:138 - DNS Checker: Validating DNS Address 'localhost' with '127.0.0.1'
03/08 11:42:01.577 [pool-3-thread-2] INFO  Node:540 - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 0
03/08 11:42:01.586 [pool-3-thread-5] INFO  Node:576 - Spawning Reply To Request Thread
java.lang.IllegalArgumentException: Calculated result exceed the range of ASCII.
    at com.iota.iri.utils.Converter.trytesToAscii(Converter.java:323)
    at com.iota.iri.pluggables.utxo.TransactionData.restoreTxs(TransactionData.java:69)
    at com.iota.iri.Iota.init(Iota.java:114)
    at com.iota.iri.IRI$IRILauncher.main(IRI.java:80)
    at com.iota.iri.IRI.main(IRI.java:34)
03/08 11:42:01.904 [main] INFO  xnio:104 - XNIO version 3.3.8.Final
03/08 11:42:01.914 [main] INFO  nio:55 - XNIO NIO Implementation Version 3.3.8.Final

**Comment by lhfbc** [comment]
This issue will be triggered after the milestone is sent.
Now we won't use milestone, so this issue can be closed, and if restore UTXO failed again, we can create a new issue.
